services:
  - type: web
    name: fake-news-app
    runtime: python
    pythonVersion: "3.11.9"  # Explicit version matching runtime.txt
    buildCommand: |
      chmod +x postinstall.sh
      ./postinstall.sh
      pip install -r requirements.txt
    startCommand: python app.py
