services:
  - type: web
    name: fake-news-app
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: |
      python -m pip install --upgrade pip setuptools==69.0.0 wheel
      pip install -r requirements.txt
    startCommand: python app.py
